export const appCopy = {
  productLabel: "Adapost Urgenta Romania",
  title: "Gaseste rapid un adapost apropiat",
  subtitle:
    "Interfata este gandita pentru telefon, lumina slaba si momente in care reteaua poate cadea.",
  actions: {
    stopLocation: "Opreste GPS",
    retryLocation: "Reincearca GPS",
    applyUpdate: "Actualizeaza si reincarca",
    findShelter: "Cauta adapost",
    emergencyGuide: "Instructiuni",
    installApp: "Instaleaza aplicatia",
    enableLocation: "Activeaza GPS",
    enableCompass: "Activeaza busola",
    manualSearch: "Cauta manual",
    chooseCounty: "Alege judetul",
    chooseTown: "Alege localitatea",
    call112: "Suna 112",
    sms113: "SMS 113",
  },
  status: {
    connectionOnline: "Cu internet",
    connectionOffline: "Fara internet",
    offlineLabels: {
      preparing: "Se salveaza offline",
      ready: "Offline pregatit",
      failed: "Offline nepregatit",
      unavailable: "Offline indisponibil",
      "update-available": "Actualizare pregatita",
    },
    offlineDetails: {
      preparing: "Se descarca interfata si datele. Pastreaza pagina deschisa pana la confirmare.",
      ready: "Interfata si datele acestei versiuni sunt salvate pentru folosire fara internet.",
      failed: "Salvarea offline nu a fost confirmata. Cand ai internet, reincarca pagina si verifica din nou.",
      unavailable: "Salvarea offline nu este disponibila aici. Foloseste versiunea publicata prin HTTPS.",
      "update-available": "O versiune noua este salvata complet. Reincarca atunci cand este sigur sa intrerupi folosirea aplicatiei.",
    },
    title: "Starea aplicatiei",
    labels: {
      offline: "Offline",
      manual: "Manual",
      private: "Privat",
    },
    offlineReady: "Pregatita pentru folosire offline dupa prima incarcare.",
    manualFallback: "Cautarea manuala dupa judet si localitate ramane disponibila.",
    localOnly: "Coordonatele raman pe dispozitiv. Fara conturi sau telemetrie.",
  },
  sections: {
    location: {
      modeLabel: "Sursa pozitiei",
      gpsMode: "GPS",
      manualMode: "Manual",
      age: "Vechimea pozitiei",
      seconds: "secunde",
      title: "Pozitia ta",
      status: "GPS sau cautare manuala",
      description:
        "Activeaza GPS cand este sigur sa folosesti telefonul sau alege manual judetul si localitatea din datele salvate offline.",
      fallback: "Alege o localitate pentru lista locala. Pozitia manuala este estimata din coordonatele adaposturilor, nu din pozitia ta exacta.",
      sourceLabels: {
        gps: "GPS activ",
        cache: "Ultima pozitie salvata",
        manual: "Localitate aleasa manual",
        none: "Fara pozitie disponibila",
      },
      permissionLabels: {
        idle: "GPS oprit",
        loading: "Se cauta pozitia",
        ready: "Pozitie disponibila",
        denied: "Permisiune refuzata",
        unavailable: "GPS indisponibil",
        error: "Eroare GPS",
        stale: "Pozitie salvata expirata",
      },
      accuracy: "Acuratete estimata",
      noAccuracy: "Acuratete necunoscuta",
      manualCountyPlaceholder: "Selecteaza judetul",
      manualTownPlaceholder: "Selecteaza localitatea",
      manualSelection: "Selectie manuala",
    },
    install: {
      title: "Instalare si offline",
      status: "Pregatire inainte de urgenta",
      description:
        "Deschide aplicatia online cel putin o data, apoi instaleaz-o din meniul browserului pentru acces rapid de pe ecranul telefonului.",
      steps: [
        "Verifica aceasta pagina cand ai internet pentru ca datele si interfata sa fie salvate pe dispozitiv.",
        "Pe Android foloseste Instalare aplicatie sau Adauga pe ecranul principal. Pe iPhone foloseste Partajare, apoi Adauga pe ecranul principal.",
        "Testeaza o reincarcare fara internet si cautarea manuala dupa judet si localitate.",
      ],
      caveat:
        "Daca ai sters datele browserului sau ai instalat pe un telefon nou, incarca din nou aplicatia online inainte sa te bazezi pe modul offline.",
    },
    shelter: {
      manualTitle: "Adaposturi in localitatea aleasa",
      manualDescription: "Lista locala pastreaza starea fiecarui adapost din datele sursa. Un adapost partial sau nefunctional nu este confirmat ca utilizabil.",
      manualDistanceNote: "Distante estimate in linie dreapta de la pozitia aproximativa a localitatii, nu de la tine si nu pe un traseu. Starea si accesul nu sunt verificate in timp real.",
      noLocalFunctional: "Niciun adapost local cu coordonate coerente nu este marcat functional in datele disponibile. Aceasta nu confirma lipsa unui adapost utilizabil; urmeaza informatiile autoritatilor.",
      localListLabel: "Adaposturi din localitatea aleasa",
      alternativeLabel: "Alternativa functionala din alta localitate",
      alternativeNote: "Inregistrare marcata functional in sursa, in afara localitatii alese. Nu este o recomandare de deplasare; verifica accesul si instructiunile autoritatilor.",
      suspectCoordinate: "Coordonate posibil neconcordante cu celelalte adaposturi din localitate. Adresa este pastrata pentru verificare; distanta si directia nu sunt fiabile.",
      distanceUncertain: "coordonate de verificat",
      title: "Adapost recomandat",
      status: "Recomandare calculata local",
      description:
        "Recomandarea favorizeaza cel mai apropiat adapost functional si marcheaza explicit adaposturile nefunctionale.",
      listTitle: "Lista apropiata",
      listPlaceholder: "Activeaza GPS sau alege manual o localitate pentru a vedea adaposturi apropiate.",
      capacityUnknown: "capacitate necunoscuta",
      capacityPeople: "persoane",
      primaryLabel: "Recomandare principala",
      nearestLabel: "Alte adaposturi apropiate",
      statusLabels: {
        functional: "functional",
        partial: "partial",
        unknown: "status necunoscut",
        nonfunctional: "nefunctional",
      },
      typeLabels: {
        public: "public",
        private: "privat",
        unknown: "tip necunoscut",
      },
      fields: {
        distance: "Distanta",
        town: "Localitate",
        capacity: "Capacitate",
        access: "Acces",
      },
    },
    compass: {
      title: "Directie catre adapost",
      status: "Busola telefonului",
      directionPrefix: "Mergi aproximativ spre",
      manualDirectionPrefix: "Directie estimata de la pozitia localitatii:",
      headingPrefix: "Telefonul indica",
      headingUnavailable: "Busola telefonului nu este disponibila acum.",
      secondaryAid:
        "Foloseste directia ca ajutor secundar. Adresa adapostului si instructiunile autoritatilor raman prioritare.",
      fields: {
        compass: "Stare busola",
      },
      cardinalLabels: {
        N: "nord",
        NE: "nord-est",
        E: "est",
        SE: "sud-est",
        S: "sud",
        SW: "sud-vest",
        W: "vest",
        NW: "nord-vest",
      },
      statusLabels: {
        idle: "busola oprita",
        listening: "se asteapta orientarea telefonului",
        ready: "busola disponibila",
        readyCalibrated: "busola calibrata",
        "permission-required": "permisiune necesara",
        denied: "permisiune refuzata",
        unavailable: "busola indisponibila",
        error: "eroare busola",
        needsCalibration: "calibrare recomandata",
      },
    },
    emergency: {
      title: "Instructiuni de urgenta",
      description:
        "Pastreaza instructiunile la indemana si urmeaza autoritatile cand informatiile oficiale difera.",
    },
    source: {
      title: "Sursa datelor",
      reviewed: "Date adaposturi vendorizate",
      official: "Sursa oficiala IGSU",
      repository: "Set JSON de referinta",
      disclaimer:
        "Datele pot deveni depasite. In teren, indicatiile 112, RO-Alert, DSU, IGSU si ale echipelor de interventie au prioritate.",
    },
  },
  navigation: {
    primaryLabel: "Navigare principala",
    status: "Stare",
    install: "Offline",
    shelter: "Adapost",
    emergency: "Urgenta",
  },
  accessibility: {
    skipToContent: "Sari la continut",
    primaryActions: "Actiuni principale",
  },
} as const;
